# Generated by Django 4.0.1 on 2022-04-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=30)),
                ('mobile_number', models.BigIntegerField()),
                ('adar', models.BigIntegerField()),
                ('bank_holder_name', models.CharField(max_length=30)),
                ('account_number', models.BigIntegerField()),
                ('ifsc_code', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
