# Generated by Django 4.0.1 on 2022-04-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_reseller'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reseller',
            table='reseller',
        ),
    ]
