# Generated by Django 4.0.1 on 2022-04-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_reseller_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseller',
            old_name='adar',
            new_name='adhar_num',
        ),
    ]
